### ISSUE TITLE
Surge crashes Renoise - Debian 10 

### ISSUE THREAD

**Issue by codecollider** [surge-synthesizer/surge-synthesizer.github.io#114] opened 2019-10-13 14:41 UTC
Hi, 

I compiled surge in Debian 10 and use it together with Renoise. It frequently crashes with this window:

https://i.imgur.com/Z835J1v.png

Last lines I see in the terminal are below. I just copied the .so file into my home user folder and the presets in /Documents/Surge. 

BTW: Is it possible to deactivate the warning that no presets are found in /usr/ ... ? 

Cheers
Marco

`renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
^CRenoise LOG> Application: Caught signal:2 - Terminating...
Renoise LOG> Application: Saving a backup...
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
Renoise LOG> VstWindow: Closing the Editor...
Renoise LOG> VstWindow: Editor was closed
Renoise LOG> Application: Exit...
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
renoise: src/common/thread/CriticalSection.h:33: void Surge::CriticalSection::enter(): Assertion `!(refcount > 10)' failed.
Renoise LOG> Shut down: Stopped the Player
Renoise LOG> MIDI: Shut down: Closing all acquired MIDI devices...
Renoise LOG> MIDI: Shutting down MIDI server...
Renoise LOG> MIDI-IO: Closing MIDI in device 'MPK Mini Mk II MIDI 1'...
Renoise LOG> MIDI-IO: Shutting down the MIDI sequencers...
Renoise LOG> Shut down: Stopped and released all MIDI-Devices
Renoise LOG> Jack: Deactivate...
Renoise LOG> Jack: Releasing port 'renoise:input_01_left'
Renoise LOG> Jack: Releasing port 'renoise:input_01_right'
Renoise LOG> Jack: Releasing port 'renoise:output_01_left'
Renoise LOG> Jack: Releasing port 'renoise:output_01_right'
Renoise LOG> Jack: Close...
^CRenoise LOG> Application: Caught signal:2 - Terminating...
Renoise LOG> Jack: Jack was released
Renoise LOG> Shut down: Stopped and released the active Audio-Device
Renoise LOG> Shut down: Destroyed the Player
Renoise LOG> Shut down: Destroyed the Document
Renoise LOG> Shut down: Destroyed the GraphPort
Renoise LOG> Shut down: Saving the Preferences
Renoise LOG> Shut down: Destroyed the Preferences
Renoise LOG> Shut down: App is down
Renoise LOG> Application: Exit OK
`

**Comment by baconpaul** [comment] 2019-10-13 21:41
Closing as a dupe of https://github.com/surge-synthesizer/surge/issues/1247 And I offered some thoughts over there

**Closed by baconpaul** 2019-10-13 21:41 UTC
